export let column = [
  {
    field: 'TaskID',
    headerText: 'Player Jersey',
    width: '180',
    textAlign: 'center',
    isFrozen: false,
  },
  {
    field: 'FIELD1',
    headerText: 'Player Name',
    width: '200',
    textAlign: 'left',
    isFrozen: false,
  },
  {
    field: 'FIELD2',
    headerText: 'Year',
    width: '100',
    format: 'yMd',
    textAlign: 'Right',
    isFrozen: false,
  },
  {
    field: 'FIELD3',
    headerText: 'Stint',
    width: '80',
    textAlign: 'Right',
    isFrozen: false,
  },
  {
    field: 'FIELD4',
    headerText: 'TIMID',
    width: '80',
    textAlign: 'Right',
    isFrozen: false,
  },
];

export let backCol = [
  {
    field: 'TaskID',
    headerText: 'Player Jersey',
    dataType: null,
    width: 200,
    defaultValue: null,
    isFrozen: false,
    textAlign: 'center',
  },
  {
    field: 'FIELD1',
    headerText: 'Player Name',
    dataType: null,
    width: 200,
    defaultValue: null,
    isFrozen: false,
    textAlign: 'center',
  },
  {
    field: 'FIELD2',
    headerText: 'Year',
    dataType: null,
    width: 200,
    defaultValue: null,
    isFrozen: false,
    textAlign: 'center',
  },
  {
    field: 'FIELD3',
    headerText: 'STINT',
    dataType: null,
    width: 200,
    defaultValue: null,
    isFrozen: false,
    textAlign: 'center',
  },
  {
    field: 'FIELD4',
    headerText: 'TIMID',
    dataType: null,
    width: 200,
    defaultValue: null,
    isFrozen: false,
    textAlign: 'center',
  },
];
