/**
 * TreeGrid DataSource
 */
export let htmlData: Object[] = [
  {
    taskID: '<span>1</span>',
    taskName: 'Planning',
    startDate: new Date('02/03/2017'),
    endDate: new Date('02/07/2017'),
    progress: 100,
    duration: 5,
    priority: 'Normal',
    approved: false,
    subtasks: [
      {
        taskID: '<span>2</span>',
        taskName: 'Plan timeline',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 3,
        taskName: 'Plan budget',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 4,
        taskName: 'Allocate resources',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 5,
        taskName: 'Planning complete',
        startDate: new Date('02/07/2017'),
        endDate: new Date('02/07/2017'),
        duration: 0,
        progress: 0,
        priority: 'Low',
        approved: true,
      },
    ],
  },
  {
    taskID: '<span>6</span>',
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    duration: 3,
    progress: 86,
    priority: 'High',
    approved: false,
    subtasks: [
      {
        taskID: 7,
        taskName: 'Software Specification',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 60,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 8,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: '<span>9</span>',
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 10,
        taskName: 'Design Documentation',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'High',
        approved: true,
      },
      {
        taskID: 11,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: 0,
        priority: 'Normal',
        approved: true,
      },
    ],
  },
  {
    taskID: 12,
    taskName: 'Implementation Phase',
    startDate: new Date('02/17/2017'),
    endDate: new Date('02/27/2017'),
    priority: 'Normal',
    approved: false,
    duration: 11,
    progress: 66,
    subtasks: [
      {
        taskID: 13,
        taskName: 'Phase 1',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'High',
        approved: false,
        progress: 50,
        duration: 11,
        subtasks: [
          {
            taskID: 14,
            taskName: 'Implementation Module 1',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'Normal',
            duration: 11,
            progress: 10,
            approved: false,
            subtasks: [
              {
                taskID: 15,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 16,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
              {
                taskID: 17,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 18,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: false,
              },
              {
                taskID: 19,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 20,
                taskName: 'Phase 1 complete',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
            ],
          },
        ],
      },
      {
        taskID: 21,
        taskName: 'Phase 2',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/28/2017'),
        priority: 'High',
        approved: false,
        duration: 12,
        progress: 60,
        subtasks: [
          {
            taskID: 22,
            taskName: 'Implementation Module 2',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/28/2017'),
            priority: 'Critical',
            approved: false,
            duration: 12,
            progress: 90,
            subtasks: [
              {
                taskID: 23,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/20/2017'),
                duration: 4,
                progress: '50',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 24,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/20/2017'),
                duration: 4,
                progress: '50',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 25,
                taskName: 'Testing',
                startDate: new Date('02/21/2017'),
                endDate: new Date('02/24/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 26,
                taskName: 'Bug fix',
                startDate: new Date('02/25/2017'),
                endDate: new Date('02/26/2017'),
                duration: 2,
                progress: '0',
                priority: 'Low',
                approved: false,
              },
              {
                taskID: 27,
                taskName: 'Customer review meeting',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/28/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 28,
                taskName: 'Phase 2 complete',
                startDate: new Date('02/28/2017'),
                endDate: new Date('02/28/2017'),
                duration: 0,
                progress: '50',
                priority: 'Normal',
                approved: false,
              },
            ],
          },
        ],
      },

      {
        taskID: 29,
        taskName: 'Phase 3',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'Normal',
        approved: false,
        duration: 11,
        progress: 30,
        subtasks: [
          {
            taskID: 30,
            taskName: 'Implementation Module 3',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'High',
            approved: false,
            duration: 11,
            progress: 60,
            subtasks: [
              {
                taskID: 31,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
              {
                taskID: 32,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Normal',
                approved: false,
              },
              {
                taskID: 33,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 34,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 35,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 36,
                taskName: 'Phase 3 complete',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '50',
                priority: 'Critical',
                approved: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

export let summaryRowData: Object[] = [
  {
    FreightID: 'CX2389NK',
    FreightName: 'Maersk Edibles Co.',
    TotalUnits: 59,
    TotalCosts: 278,
    UnitWeight: 241,
    children: [
      {
        FreightID: 'QW4567OP',
        FreightName: 'Chang',
        TotalUnits: 12,
        TotalCosts: 140,
        UnitWeight: 50,
      },
      {
        FreightID: 'QW3458BH',
        FreightName: 'Aniseed Syrup',
        TotalUnits: 89,
        TotalCosts: 590,
        UnitWeight: 87,
      },
      {
        FreightID: 'QW8967OH',
        FreightName: 'Chef Anton',
        TotalUnits: 46,
        TotalCosts: 460,
        UnitWeight: 54,
      },
      {
        FreightID: 'QW6549NJ',
        FreightName: 'Chef Antons Gumbo Mix',
        TotalUnits: 34,
        TotalCosts: 590,
        UnitWeight: 50,
      },
    ],
  },
  {
    FreightID: 'DW8954IO',
    FreightName: 'Aeon fitness inc.',
    TotalUnits: 172,
    TotalCosts: 24,
    UnitWeight: 296,
    children: [
      {
        FreightID: 'UF5647YH',
        FreightName: 'Reebox CrossFit Back Bay',
        TotalUnits: 60,
        TotalCosts: 870,
        UnitWeight: 73,
      },
      {
        FreightID: 'UF1290LK',
        FreightName: 'The Green Microgym',
        TotalUnits: 56,
        TotalCosts: 876,
        UnitWeight: 90,
      },
      {
        FreightID: 'UF8956KU',
        FreightName: 'DeFrancos',
        TotalUnits: 45,
        TotalCosts: 458,
        UnitWeight: 68,
      },
      {
        FreightID: 'UF7464JK',
        FreightName: 'Westside Barbell',
        TotalUnits: 25,
        TotalCosts: 231,
        UnitWeight: 65,
      },
    ],
  },
  {
    FreightID: 'EJ9456KN',
    FreightName: 'Sun technologies inc',
    TotalUnits: 33,
    TotalCosts: 229,
    UnitWeight: 192,
    children: [
      {
        FreightID: 'GH2367OP',
        FreightName: 'Haier Group',
        TotalUnits: 78,
        TotalCosts: 678,
        UnitWeight: 23,
      },
      {
        FreightID: 'GH4309TH',
        FreightName: 'Panda Electronics',
        TotalUnits: 90,
        TotalCosts: 790,
        UnitWeight: 48,
      },
      {
        FreightID: 'GH3494SD',
        FreightName: 'Jiangsu Etern',
        TotalUnits: 36,
        TotalCosts: 435,
        UnitWeight: 56,
      },
      {
        FreightID: 'GH3213FR',
        FreightName: 'Zhejiang Fuchunjiang',
        TotalUnits: 12,
        TotalCosts: 278,
        UnitWeight: 65,
      },
    ],
  },
];

export let summaryData: Object[] = [
  {
    ID: '1',
    Name: 'Order 1',
    units: '1395',
    unitPrice: '47.00',
    price: 133.66,
    category: 'Seafoods',
    subtasks: [
      {
        ID: '1.1',
        Name: 'Mackerel',
        category: 'Frozen seafood',
        units: '235',
        unitPrice: '12.26',
        price: 28.2,
      },
      {
        ID: '1.2',
        Name: 'Yellowfin Tuna',
        category: 'Frozen seafood',
        units: '324',
        unitPrice: '18.45',
        price: 25.92,
      },
      {
        ID: '1.3',
        Name: 'Herrings',
        category: 'Frozen seafood',
        units: '488',
        unitPrice: '11.45',
        price: 52.68,
      },
      {
        ID: '1.4',
        Name: 'Preserved Olives',
        category: 'Edible',
        units: '125',
        unitPrice: '19.56',
        price: 11.25,
      },
      {
        ID: '1.5',
        Name: 'Sweet corn Frozen',
        category: 'Edible',
        units: '223',
        unitPrice: '12.34',
        price: 15.61,
      },
    ],
  },
  {
    ID: '2',
    Name: 'Order 2',
    units: '1944',
    unitPrice: '58.45',
    price: 21.33,
    category: 'Products',
    subtasks: [
      {
        ID: '2.1',
        Name: 'Tilapias',
        category: 'Frozen seafood',
        units: '278',
        unitPrice: '15.45',
        price: 41.7,
      },
      {
        ID: '2.2',
        Name: 'White Shrimp',
        category: 'Frozen seafood',
        units: '560',
        unitPrice: '17.66',
        price: 39.2,
      },
      {
        ID: '2.3',
        Name: 'Fresh Cheese',
        category: 'Dairy',
        units: '323',
        unitPrice: '12.35',
        price: 38.76,
      },
      {
        ID: '2.4',
        Name: 'Blue Veined Cheese',
        category: 'Dairy',
        units: '370',
        unitPrice: '15.77',
        price: 55.5,
      },
      {
        ID: '2.5',
        Name: 'Butter',
        category: 'Dairy',
        units: '413',
        unitPrice: '19.45',
        price: 37.17,
      },
    ],
  },
  {
    ID: '3',
    Name: 'Order 3',
    units: '1120',
    unitPrice: '33.45',
    price: 10.8,
    category: 'Crystals',
    subtasks: [
      {
        ID: '3.1',
        Name: 'Lead glassware',
        category: 'Solid crystals',
        units: '542',
        unitPrice: '19.56',
        price: 32.52,
      },
      {
        ID: '3.2',
        Name: 'Pharmaceutical Glassware',
        category: 'Solid crystals',
        units: '324',
        unitPrice: '11.36',
        price: 35.64,
      },
      {
        ID: '3.3',
        Name: 'Glass beads',
        category: 'Solid crystals',
        units: '254',
        unitPrice: '16.11',
        price: 40.64,
      },
    ],
  },
];
export let sampleData: Object[] = [
  {
    taskID: 1,
    taskName: 'Planning',
    startDate: new Date('02/03/2017'),
    endDate: new Date('02/07/2017'),
    progress: 100,
    duration: 5,
    priority: 'Normal',
    approved: false,
    subtasks: [
      {
        taskID: 2,
        taskName: 'Plan timeline',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 3,
        taskName: 'Plan budget',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 4,
        taskName: 'Allocate resources',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 5,
        taskName: 'Planning complete',
        startDate: new Date('02/07/2017'),
        endDate: new Date('02/07/2017'),
        duration: 0,
        progress: 0,
        priority: 'Low',
        approved: true,
      },
    ],
  },
  {
    taskID: 6,
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    duration: 3,
    progress: 86,
    priority: 'High',
    approved: false,
    subtasks: [
      {
        taskID: 7,
        taskName: 'Software Specification',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 60,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 8,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 9,
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 10,
        taskName: 'Design Documentation',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'High',
        approved: true,
      },
      {
        taskID: 11,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: 0,
        priority: 'Normal',
        approved: true,
      },
    ],
  },
  {
    taskID: 12,
    taskName: 'Implementation Phase',
    startDate: new Date('02/17/2017'),
    endDate: new Date('02/27/2017'),
    priority: 'Normal',
    approved: false,
    duration: 11,
    progress: 66,
    subtasks: [
      {
        taskID: 13,
        taskName: 'Phase 1',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'High',
        approved: false,
        progress: 50,
        duration: 11,
        subtasks: [
          {
            taskID: 14,
            taskName: 'Implementation Module 1',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'Normal',
            duration: 11,
            progress: 10,
            approved: false,
            subtasks: [
              {
                taskID: 15,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 16,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
              {
                taskID: 17,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 18,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: false,
              },
              {
                taskID: 19,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 20,
                taskName: 'Phase 1 complete',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
            ],
          },
        ],
      },
      {
        taskID: 21,
        taskName: 'Phase 2',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/28/2017'),
        priority: 'High',
        approved: false,
        duration: 12,
        progress: 60,
        subtasks: [
          {
            taskID: 22,
            taskName: 'Implementation Module 2',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/28/2017'),
            priority: 'Critical',
            approved: false,
            duration: 12,
            progress: 90,
            subtasks: [
              {
                taskID: 23,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/20/2017'),
                duration: 4,
                progress: '50',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 24,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/20/2017'),
                duration: 4,
                progress: '50',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 25,
                taskName: 'Testing',
                startDate: new Date('02/21/2017'),
                endDate: new Date('02/24/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 26,
                taskName: 'Bug fix',
                startDate: new Date('02/25/2017'),
                endDate: new Date('02/26/2017'),
                duration: 2,
                progress: '0',
                priority: 'Low',
                approved: false,
              },
              {
                taskID: 27,
                taskName: 'Customer review meeting',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/28/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 28,
                taskName: 'Phase 2 complete',
                startDate: new Date('02/28/2017'),
                endDate: new Date('02/28/2017'),
                duration: 0,
                progress: '50',
                priority: 'Normal',
                approved: false,
              },
            ],
          },
        ],
      },

      {
        taskID: 29,
        taskName: 'Phase 3',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'Normal',
        approved: false,
        duration: 11,
        progress: 30,
        subtasks: [
          {
            taskID: 30,
            taskName: 'Implementation Module 3',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'High',
            approved: false,
            duration: 11,
            progress: 60,
            subtasks: [
              {
                taskID: 31,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
              {
                taskID: 32,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Normal',
                approved: false,
              },
              {
                taskID: 33,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 34,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 35,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 36,
                taskName: 'Phase 3 complete',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '50',
                priority: 'Critical',
                approved: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

export let textWrapData: Object[] = [
  {
    taskID: 1,
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    duration: 3,
    progress: 86,
    priority: 'High',
    approved: false,
    subtasks: [
      {
        taskID: 2,
        taskName: 'Specification of Software',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 60,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 3,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 4,
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        approved: true,
        priority: 'Normal',
      },
      {
        taskID: 5,
        taskName: 'Design Document',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        approved: true,
        priority: 'Critical',
      },
      {
        taskID: 6,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: 0,
        priority: 'Normal',
        approved: true,
      },
    ],
  },
  {
    taskID: 7,
    taskName: 'Implementation Phase',
    startDate: new Date('02/17/2017'),
    endDate: new Date('02/27/2017'),
    priority: 'Normal',
    approved: false,
    duration: 11,
    progress: 66,
    subtasks: [
      {
        taskID: 8,
        taskName: 'Phase 1',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'High',
        approved: false,
        duration: 11,
        progress: 86,
        subtasks: [
          {
            taskID: 9,
            taskName: 'Implementation Module 1',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'Normal',
            duration: 11,
            progress: 96,
            approved: false,
            subtasks: [
              {
                taskID: 10,
                taskName: 'Development',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 12,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 13,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: false,
              },
              {
                taskID: 14,
                taskName: 'Get approval from customer',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 15,
                taskName: 'Completed',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '0',
                priority: 'Low',
                approved: true,
              },
            ],
          },
        ],
      },

      {
        taskID: 16,
        taskName: 'Phase 2',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/28/2017'),
        priority: 'High',
        approved: false,
        duration: 12,
        progress: 50,
        subtasks: [
          {
            taskID: 17,
            taskName: 'Implementation Module 2',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/28/2017'),
            priority: 'Critical',
            approved: false,
            duration: 12,
            progress: 56,
            subtasks: [
              {
                taskID: 18,
                taskName: 'Development',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/20/2017'),
                duration: 4,
                progress: '50',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 20,
                taskName: 'Testing',
                startDate: new Date('02/21/2017'),
                endDate: new Date('02/24/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 21,
                taskName: 'Bug fix',
                startDate: new Date('02/25/2017'),
                endDate: new Date('02/26/2017'),
                duration: 2,
                progress: '0',
                priority: 'Low',
                approved: false,
              },
              {
                taskID: 22,
                taskName: 'Get approval from customer',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/28/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 23,
                taskName: 'Completed',
                startDate: new Date('02/28/2017'),
                endDate: new Date('02/28/2017'),
                duration: 0,
                progress: '0',
                priority: 'Normal',
                approved: false,
              },
            ],
          },
        ],
      },

      {
        taskID: 24,
        taskName: 'Phase 3',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        priority: 'Normal',
        approved: false,
        duration: 11,
        progress: 50,
        subtasks: [
          {
            taskID: 25,
            taskName: 'Implementation Module 3',
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            priority: 'High',
            approved: false,
            progress: 56,
            duration: 11,
            subtasks: [
              {
                taskID: 26,
                taskName: 'Development',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                priority: 'Low',
                approved: true,
              },
              {
                taskID: 28,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                priority: 'Critical',
                approved: true,
              },
              {
                taskID: 29,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                priority: 'High',
                approved: false,
              },
              {
                taskID: 30,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                priority: 'Normal',
                approved: true,
              },
              {
                taskID: 31,
                taskName: 'Completed',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                progress: '0',
                priority: 'Critical',
                approved: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

export let textdata: Object[] = [
  {
    Name: 'Robert King',
    FullName: 'RobertKing',
    Designation: 'Chief Executive Officer',
    EmployeeID: '1',
    EmpID: 'EMP001',
    Address: '507 - 20th Ave. E.Apt. 2A, Seattle',
    Contact: '(206) 555-9857',
    Country: 'USA',
    DOB: new Date('2/15/1963'),

    Children: [
      {
        Name: 'David william',
        FullName: 'DavidWilliam',
        Designation: 'Vice President',
        EmployeeID: '2',
        EmpID: 'EMP004',
        Address: '722 Moss Bay Blvd., Kirkland',
        Country: 'USA',
        Contact: '(206) 555-3412',
        DOB: new Date('5/20/1971'),

        Children: [
          {
            Name: 'Nancy Davolio',
            FullName: 'NancyDavolio',
            Designation: 'Marketing Executive',
            EmployeeID: '3',
            EmpID: 'EMP035',
            Address: '4110 Old Redmond Rd., Redmond',
            Country: 'USA',
            Contact: '(206) 555-8122',
            DOB: new Date('3/19/1966'),
            Children: [
              {
                Name: 'Andrew Fuller',
                FullName: 'AndrewFuller',
                Designation: 'Sales Representative',
                EmployeeID: '4',
                EmpID: 'EMP045',
                Address: '14 Garrett Hill, London',
                Country: 'UK',
                Contact: '(71) 555-4848',
                DOB: new Date('9/20/1980'),
              },
              {
                Name: 'Anne Dodsworth',
                FullName: 'AnneDodsworth',
                Designation: 'Sales Representative',
                EmployeeID: '5',
                EmpID: 'EMP091',
                Address: '4726 - 11th Ave. N.E., Seattle',
                Country: 'USA',
                Contact: '(206) 555-1189',
                DOB: new Date('10/19/1989'),
              },
              {
                Name: 'Michael Suyama',
                FullName: 'MichaelSuyama',
                Designation: 'Sales Representative',
                EmployeeID: '6',
                EmpID: 'EMP110',
                Address: 'Coventry House Miner Rd., London',
                Country: 'UK',
                Contact: '(71) 555-3636',
                DOB: new Date('11/02/1987'),
              },
              {
                Name: 'Janet Leverling',
                FullName: 'JanetLeverling',
                Designation: 'Sales Coordinator',
                EmployeeID: '7',
                EmpID: 'EMP131',
                Address: 'Edgeham Hollow Winchester Way, London',
                Country: 'UK',
                Contact: '(71) 555-3636',
                DOB: new Date('11/06/1990'),
              },
            ],
          },
          {
            Name: 'Romey Wilson',
            FullName: 'RomeyWilson',
            Designation: 'Sales Executive',
            EmployeeID: '8',
            EmpID: 'EMP039',
            Address: '7 Houndstooth Rd., London',
            Country: 'UK',
            Contact: '(71) 555-3690',
            DOB: new Date('02/02/1980'),
            Children: [
              {
                Name: 'Margaret Peacock',
                FullName: 'MargaretPeacock',
                Designation: 'Sales Representative',
                EmployeeID: '9',
                EmpID: 'EMP213',
                Address: '4726 - 11th Ave. N.E., California',
                Country: 'USA',
                Contact: '(206) 555-1989',
                DOB: new Date('01/21/1986'),
              },
              {
                Name: 'Laura Callahan',
                FullName: 'LauraCallahan',
                Designation: 'Sales Coordinator',
                EmployeeID: '10',
                EmpID: 'EMP201',
                Address: 'Coventry House Miner Rd., London',
                Country: 'UK',
                Contact: '(71) 555-2222',
                DOB: new Date('12/01/1990'),
              },
              {
                Name: 'Steven Buchanan',
                FullName: 'StevenBuchanan',
                Designation: 'Sales Representative',
                EmployeeID: '11',
                EmpID: 'EMP197',
                Address: '200 Lincoln Ave, Salinas, CA 93901',
                Country: 'USA',
                Contact: '(831) 758-7408',
                DOB: new Date('03/23/1987'),
              },
              {
                Name: 'Tedd Lawson',
                FullName: 'TeddLawson',
                Designation: 'Sales Representative',
                EmployeeID: '12',
                EmpID: 'EMP167',
                Address: '200 Lincoln Ave, Salinas, CA 93901',
                Country: 'USA',
                Contact: '(831) 758-7368 ',
                DOB: new Date('08/09/1989'),
              },
            ],
          },
        ],
      },
    ],
  },
];

export let headerData: Object[] = [
  {
    taskID: 1,
    taskName: 'Planning',
    startDate: new Date('02/03/2017'),
    endDate: new Date('02/07/2017'),
    resourceId: '8',
    duration: 5,
    progress: '100',
    subtasks: [
      {
        taskID: 2,
        taskName: 'Plan timeline',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: '100',
        resourceId: '2',
      },
      {
        taskID: 3,
        taskName: 'Plan budget',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: '100',
        resourceId: '1',
      },
      {
        taskID: 4,
        taskName: 'Allocate resources',
        startDate: new Date('02/03/2017'),
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: '100',
        resourceId: '1',
      },
      {
        taskID: 5,
        taskName: 'Planning complete',
        startDate: new Date('02/07/2017'),
        endDate: new Date('02/07/2017'),
        duration: 0,
        progress: '100',
        resourceId: '7',
      },
    ],
  },
  {
    taskID: 6,
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    resourceId: '1',
    progress: '60',
    duration: 3,
    subtasks: [
      {
        taskID: 7,
        taskName: 'Software Specification',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: '60',
        predecessor: '6FS',
        resourceId: '2',
      },
      {
        taskID: 8,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: '100',
        predecessor: '6FS',
        resourceId: '3',
      },
      {
        taskID: 9,
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: '100',
        predecessor: '9FS',
        resourceId: '1',
      },
      {
        taskID: 10,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: '100',
        resourceId: '9',
      },
    ],
  },
  {
    taskID: 11,
    taskName: 'Implementation Phase',
    startDate: new Date('02/17/2017'),
    endDate: new Date('02/27/2017'),
    resourceId: '5',
    progress: '80',
    duration: 5,
    subtasks: [
      {
        taskID: 12,
        taskName: 'Phase',
        startDate: new Date('02/17/2017'),
        endDate: new Date('02/27/2017'),
        resourceId: '7',
        duration: 5,
        progress: '50',
        subtasks: [
          {
            taskID: 13,
            taskName: 'Implementation Module',
            resourceId: '3',
            progress: '50',
            duration: 3,
            startDate: new Date('02/17/2017'),
            endDate: new Date('02/27/2017'),
            subtasks: [
              {
                taskID: 14,
                taskName: 'Development Task 1',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                predecessor: '11FS',
                resourceId: '3',
              },
              {
                taskID: 15,
                taskName: 'Development Task 2',
                startDate: new Date('02/17/2017'),
                endDate: new Date('02/19/2017'),
                duration: 3,
                progress: '50',
                predecessor: '11FS',
                resourceId: '3',
              },
              {
                taskID: 16,
                taskName: 'Testing',
                startDate: new Date('02/20/2017'),
                endDate: new Date('02/21/2017'),
                duration: 2,
                progress: '0',
                predecessor: '15FS,16FS',
                resourceId: '4',
              },
              {
                taskID: 17,
                taskName: 'Bug fix',
                startDate: new Date('02/24/2017'),
                endDate: new Date('02/25/2017'),
                duration: 2,
                progress: '0',
                predecessor: '17FS',
                resourceId: '4',
              },
              {
                taskID: 18,
                taskName: 'Customer review meeting',
                startDate: new Date('02/26/2017'),
                endDate: new Date('02/27/2017'),
                duration: 2,
                progress: '0',
                predecessor: '18FS',
                resourceId: '1',
              },
              {
                taskID: 19,
                taskName: 'Phase complete',
                startDate: new Date('02/27/2017'),
                endDate: new Date('02/27/2017'),
                duration: 0,
                predecessor: '19FS',
                progress: '0',
                resourceId: '9',
              },
            ],
          },
        ],
      },
    ],
  },
];

export let stackedData: Object[] = [
  {
    orderID: '1',
    orderName: 'Order 1',
    orderDate: new Date('02/03/2017'),
    shippedDate: new Date('02/09/2017'),
    units: '1395',
    unitPrice: '47.00',
    price: 133.66,
    shipMentCategory: 'Seafood',
    subtasks: [
      {
        orderID: '1.1',
        orderName: 'Mackerel',
        shipMentCategory: 'Frozen seafood',
        units: '35',
        orderDate: new Date('03/03/2017'),
        shippedDate: new Date('03/10/2017'),
        unitPrice: '12.56',
        price: 28.2,
      },
      {
        orderID: '1.2',
        orderName: 'Yellowfin Tuna',
        shipMentCategory: 'Frozen seafood',
        units: '324',
        orderDate: new Date('05/03/2017'),
        shippedDate: new Date('05/10/2017'),
        unitPrice: '28.26',
        price: 25.92,
      },
      {
        orderID: '1.3',
        orderName: 'Herrings',
        shipMentCategory: 'Frozen seafood',
        units: '48',
        orderDate: new Date('05/08/2017'),
        shippedDate: new Date('05/15/2017'),
        unitPrice: '11.35',
        price: 52.68,
      },
      {
        orderID: '1.4',
        orderName: 'Preserved Olives',
        shipMentCategory: 'Edible',
        units: '125',
        orderDate: new Date('06/10/2017'),
        shippedDate: new Date('06/17/2017'),
        unitPrice: '29.23',
        price: 11.25,
      },
      {
        orderID: '1.5',
        orderName: 'Sweet corn Frozen',
        shipMentCategory: 'Edible',
        units: '223',
        orderDate: new Date('07/12/2017'),
        shippedDate: new Date('07/19/2017'),
        unitPrice: '47.17',
        price: 15.61,
      },
    ],
  },
  {
    orderID: '2',
    orderName: 'Order 2',
    orderDate: new Date('01/10/2018'),
    shippedDate: new Date('01/16/2018'),
    units: '1944',
    unitPrice: '58.45',
    price: 21.23,
    shipMentCategory: 'Seafood',
    subtasks: [
      {
        orderID: '2.1',
        orderName: 'Tilapias',
        shipMentCategory: 'Frozen Seafood',
        orderDate: new Date('02/05/2018'),
        shippedDate: new Date('02/12/2018'),
        units: '278',
        unitPrice: '15.25',
        price: 41.7,
      },
      {
        orderID: '2.2',
        orderName: 'White Shrimp',
        shipMentCategory: 'Frozen seafood',
        units: '560',
        orderDate: new Date('05/22/2018'),
        shippedDate: new Date('05/29/2018'),
        unitPrice: '72.45',
        price: 39.2,
      },
      {
        orderID: '2.3',
        orderName: 'Fresh Cheese',
        shipMentCategory: 'Dairy',
        units: '323',
        unitPrice: 12.45,
        orderDate: new Date('06/08/2018'),
        shippedDate: new Date('06/15/2018'),
        price: 38.76,
      },
      {
        orderID: '2.4',
        orderName: 'Blue Veined Cheese',
        shipMentCategory: 'Dairy',
        units: '370',
        unitPrice: 15.36,
        orderDate: new Date('07/10/2018'),
        shippedDate: new Date('07/17/2018'),
        price: 55.5,
      },
      {
        orderID: '2.5',
        orderName: 'Butter',
        shipMentCategory: 'Dairy',
        units: '413',
        unitPrice: '19.35',
        orderDate: new Date('09/18/2018'),
        shippedDate: new Date('09/25/2018'),
        price: 37.17,
      },
    ],
  },
  {
    orderID: '3',
    orderName: 'Order 3',
    orderDate: new Date('09/10/2018'),
    shippedDate: new Date('09/20/2018'),
    units: '1120',
    unitPrice: '33.34',
    price: 10.8,
    shipMentCategory: 'Seafood',
    subtasks: [
      {
        orderID: '3.1',
        orderName: 'Lead glassware',
        shipMentCategory: 'Solid crystals',
        orderDate: new Date('02/07/2018'),
        shippedDate: new Date('02/14/2018'),
        units: '542',
        unitPrice: '46.45',
        price: 32.52,
      },
      {
        orderID: '3.2',
        orderName: 'Pharmaceutical',
        shipMentCategory: 'Solid crystals',
        orderDate: new Date('04/19/2018'),
        shippedDate: new Date('04/26/2018'),
        units: '324',
        unitPrice: '11.56',
        price: 35.64,
      },
      {
        orderID: '3.3',
        orderName: 'Glass beads',
        shipMentCategory: 'Solid crystals',
        units: '254',
        orderDate: new Date('05/22/2018'),
        shippedDate: new Date('03/22/2018'),
        unitPrice: '16.25',
        price: 40.64,
      },
    ],
  },
];

export let formatData: Object[] = [
  {
    orderID: '1',
    orderName: 'Order 1',
    orderDate: new Date('02/03/2017'),
    shippedDate: new Date('10/03/2018'),
    units: '1395',
    unitPrice: '47',
    price: 133.66,
    Category: 'seafood',
    subtasks: [
      {
        orderID: '1.1',
        orderName: 'Mackerel',
        Category: 'Frozen seafood',
        units: '235',
        orderDate: new Date('02/03/2017'),
        shippedDate: new Date('05/13/2018'),
        unitPrice: '12',
        price: 28.2,
      },
      {
        orderID: '1.2',
        orderName: 'Yellowfin Tuna',
        Category: 'Frozen seafood',
        units: '324',
        orderDate: new Date('05/03/2017'),
        shippedDate: new Date('05/22/2018'),
        unitPrice: '8',
        price: 25.92,
      },
      {
        orderID: '1.3',
        orderName: 'Herrings',
        Category: 'Frozen seafood',
        units: '488',
        orderDate: new Date('10/03/2017'),
        shippedDate: new Date('10/14/2018'),
        unitPrice: '11',
        price: 52.68,
      },
      {
        orderID: '1.4',
        orderName: 'Preserved Olives',
        Category: 'Edible',
        units: '125',
        orderDate: new Date('08/03/2017'),
        shippedDate: new Date('08/03/2018'),
        unitPrice: '9',
        price: 11.25,
      },
      {
        orderID: '1.5',
        orderName: 'Sweet corn Frozen',
        Category: 'Edible',
        units: '223',
        orderDate: new Date('09/03/2017'),
        shippedDate: new Date('09/03/2018'),
        unitPrice: '7',
        price: 15.61,
      },
    ],
  },
  {
    orderID: '2',
    orderName: 'Order 2',
    orderDate: new Date('05/03/2017'),
    shippedDate: new Date('03/15/2018'),
    units: '1944',
    unitPrice: '58',
    price: 212.33,
    Category: 'seafood',
    subtasks: [
      {
        orderID: '2.1',
        orderName: 'Tilapias',
        Category: 'Frozen seafood',
        orderDate: new Date('03/05/2017'),
        shippedDate: new Date('03/15/2018'),
        units: '278',
        unitPrice: '15',
        price: 41.7,
      },
      {
        orderID: '2.2',
        orderName: 'White Shrimp',
        Category: 'Frozen seafood',
        units: '560',
        orderDate: new Date('07/05/2017'),
        shippedDate: new Date('03/15/2018'),
        unitPrice: '7',
        price: 39.2,
      },
      {
        orderID: '2.3',
        orderName: 'Fresh Cheese',
        Category: 'Dairy',
        units: '323',
        unitPrice: '12',
        orderDate: new Date('09/03/2017'),
        shippedDate: new Date('09/19/2018'),
        price: 38.76,
      },
      {
        orderID: '2.4',
        orderName: 'Blue Veined Cheese',
        Category: 'Dairy',
        units: '370',
        unitPrice: '15',
        orderDate: new Date('11/03/2017'),
        shippedDate: new Date('11/13/2018'),
        price: 55.5,
      },
      {
        orderID: '2.5',
        orderName: 'Butter',
        Category: 'Dairy',
        units: '413',
        unitPrice: '9',
        orderDate: new Date('10/23/2017'),
        shippedDate: new Date('10/23/2018'),
        price: 37.17,
      },
    ],
  },
  {
    orderID: '3',
    orderName: 'Order 3',
    orderDate: new Date('03/10/2017'),
    shippedDate: new Date('03/20/2018'),
    units: '1120',
    unitPrice: '33',
    price: '108.80',
    Category: 'seafood',
    subtasks: [
      {
        orderID: '3.1',
        orderName: 'Lead glassware',
        Category: 'Solid crystals',
        orderDate: new Date('08/03/2017'),
        shippedDate: new Date('03/18/2018'),
        units: '542',
        unitPrice: '6',
        price: '32.52',
      },
      {
        orderID: '3.2',
        orderName: 'Pharmaceutical Glassware',
        Category: 'Solid crystals',
        orderDate: new Date('03/10/2017'),
        shippedDate: new Date('03/20/2018'),
        units: '324',
        unitPrice: '11',
        price: '35.64',
      },
      {
        orderID: '3.3',
        orderName: 'Glass beads',
        Category: 'Solid crystals',
        units: '254',
        orderDate: new Date('03/02/2017'),
        shippedDate: new Date('03/22/2018'),
        unitPrice: '16',
        price: '40.64',
      },
    ],
  },
];

export let sortData: Object[] = [
  {
    orderID: '1',
    orderName: 'Order 1',
    orderDate: new Date('02/03/2017'),
    shippedDate: new Date('02/09/2017'),
    units: '1395',
    unitPrice: '47',
    price: 133.66,
    Category: 'Seafoods',
    subtasks: [
      {
        orderID: '1.1',
        orderName: 'Mackerel',
        Category: 'Frozen seafood',
        units: '235',
        orderDate: new Date('03/03/2017'),
        shippedDate: new Date('03/10/2017'),
        unitPrice: '12',
        price: 28.2,
      },
      {
        orderID: '1.2',
        orderName: 'Yellowfin Tuna',
        Category: 'Frozen seafood',
        units: '324',
        orderDate: new Date('04/05/2017'),
        shippedDate: new Date('04/12/2017'),
        unitPrice: '8',
        price: 25.92,
      },
      {
        orderID: '1.3',
        orderName: 'Herrings',
        Category: 'Frozen seafood',
        units: '488',
        orderDate: new Date('05/08/2017'),
        shippedDate: new Date('05/15/2017'),
        unitPrice: '11',
        price: 52.68,
      },
      {
        orderID: '1.4',
        orderName: 'Preserved Olives',
        Category: 'Edible',
        units: '125',
        orderDate: new Date('06/10/2017'),
        shippedDate: new Date('06/17/2017'),
        unitPrice: '9',
        price: 11.25,
      },
      {
        orderID: '1.5',
        orderName: 'Sweet corn Frozen',
        Category: 'Edible',
        units: '223',
        orderDate: new Date('07/12/2017'),
        shippedDate: new Date('07/19/2019'),
        unitPrice: '7',
        price: 15.61,
      },
    ],
  },
  {
    orderID: '2',
    orderName: 'Order 2',
    orderDate: new Date('01/10/2018'),
    shippedDate: new Date('01/16/2018'),
    units: '1944',
    unitPrice: '58',
    price: 212.33,
    Category: 'products',
    subtasks: [
      {
        orderID: '2.1',
        orderName: 'Tilapias',
        Category: 'Frozen seafood',
        orderDate: new Date('02/05/2018'),
        shippedDate: new Date('02/12/2018'),
        units: '278',
        unitPrice: '15',
        price: 41.7,
      },
      {
        orderID: '2.2',
        orderName: 'White Shrimp',
        Category: 'Frozen seafood',
        units: '560',
        orderDate: new Date('05/22/2018'),
        shippedDate: new Date('05/29/2018'),
        unitPrice: '7',
        price: 39.2,
      },
      {
        orderID: '2.3',
        orderName: 'Fresh Cheese',
        Category: 'Dairy',
        units: '323',
        unitPrice: '12',
        orderDate: new Date('06/08/2018'),
        shippedDate: new Date('06/15/2018'),
        price: 38.76,
      },
      {
        orderID: '2.4',
        orderName: 'Blue Veined Cheese',
        Category: 'Dairy',
        units: '370',
        unitPrice: '15',
        orderDate: new Date('07/10/2018'),
        shippedDate: new Date('07/17/2018'),
        price: 55.5,
      },
      {
        orderID: '2.5',
        orderName: 'Butter',
        Category: 'Dairy',
        units: '413',
        unitPrice: '9',
        orderDate: new Date('09/18/2018'),
        shippedDate: new Date('09/25/2018'),
        price: 37.17,
      },
    ],
  },
  {
    orderID: '3',
    orderName: 'Order 3',
    orderDate: new Date('09/10/2018'),
    shippedDate: new Date('09/20/2018'),
    units: '1120',
    unitPrice: '33',
    price: 108.8,
    Category: 'Crystals',
    subtasks: [
      {
        orderID: '3.1',
        orderName: 'Lead glassware',
        Category: 'Solid crystals',
        orderDate: new Date('02/07/2018'),
        shippedDate: new Date('02/14/2018'),
        units: '542',
        unitPrice: '6',
        price: 32.52,
      },
      {
        orderID: '3.2',
        orderName: 'Pharmaceutical Glassware',
        Category: 'Solid crystals',
        orderDate: new Date('04/19/2018'),
        shippedDate: new Date('04/26/2018'),
        units: '324',
        unitPrice: '11',
        price: 35.64,
      },
      {
        orderID: '3.3',
        orderName: 'Glass beads',
        Category: 'Solid crystals',
        units: '254',
        orderDate: new Date('05/22/2018'),
        shippedDate: new Date('03/22/2018'),
        unitPrice: '16',
        price: 40.64,
      },
    ],
  },
];

export let lockRowDropDownData: number[] = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
];

export let projectData: Object[] = [
  {
    TaskID: 1,
    TaskName: 'Parent Task 1',
    StartDate: new Date('02/23/2017'),
    Duration: 3,
    Priority: 'Normal',
    EndDate: new Date('02/27/2017'),
    Progress: '40',
  },
  {
    TaskID: 2,
    TaskName: 'Child Task 1',
    StartDate: new Date('02/23/2017'),
    Duration: 4,
    Priority: 'Low',
    EndDate: new Date('02/27/2017'),
    Progress: '40',
    parentID: 1,
  },
  {
    TaskID: 3,
    TaskName: 'Child Task 2',
    StartDate: new Date('02/23/2017'),
    Duration: 2,
    Priority: 'Normal',
    EndDate: new Date('02/27/2017'),
    Progress: '40',
    parentID: 1,
  },
  {
    TaskID: 4,
    TaskName: 'Child Task 3',
    StartDate: new Date('02/23/2017'),
    Duration: 2,
    Priority: 'Low',
    EndDate: new Date('02/27/2017'),
    Progress: '40',
    parentID: 1,
  },
  {
    TaskID: 5,
    TaskName: 'Parent Task 2',
    StartDate: new Date('03/14/2017'),
    Duration: 6,
    Priority: 'Normal',
    EndDate: new Date('03/18/2017'),
    Progress: '40',
  },
  {
    TaskID: 6,
    TaskName: 'Child Task 1',
    StartDate: new Date('03/02/2017'),
    Duration: 11,
    Priority: 'High',
    EndDate: new Date('03/06/2017'),
    Progress: '40',
    parentID: 5,
  },
  {
    TaskID: 7,
    TaskName: 'Child Task 2',
    StartDate: new Date('03/02/2017'),
    Duration: 7,
    Priority: 'Critical',
    EndDate: new Date('03/06/2017'),
    Progress: '40',
    parentID: 5,
  },
  {
    TaskID: 8,
    TaskName: 'Child Task 3',
    StartDate: new Date('03/02/2017'),
    Duration: 10,
    Priority: 'Breaker',
    EndDate: new Date('03/06/2017'),
    Progress: '40',
    parentID: 5,
  },
  {
    TaskID: 9,
    TaskName: 'Child Task 4',
    StartDate: new Date('03/02/2017'),
    Duration: 15,
    Priority: 'High',
    EndDate: new Date('03/06/2017'),
    Progress: '40',
    parentID: 5,
  },
  {
    TaskID: 10,
    TaskName: 'Parent Task 3',
    StartDate: new Date('03/09/2017'),
    Duration: 17,
    Priority: 'Breaker',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
  },
  {
    TaskID: 11,
    TaskName: 'Child Task 1',
    StartDate: new Date('03/9/2017'),
    Duration: 0,
    Priority: 'Low',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
    parentID: 10,
  },
  {
    TaskID: 12,
    TaskName: 'Child Task 2',
    StartDate: new Date('03/9/2017'),
    Duration: 10,
    Priority: 'Breaker',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
    parentID: 10,
  },
  {
    TaskID: 13,
    TaskName: 'Child Task 3',
    StartDate: new Date('03/9/2017'),
    Duration: 11,
    Priority: 'Normal',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
    parentID: 10,
  },
  {
    TaskID: 14,
    TaskName: 'Child Task 4',
    StartDate: new Date('03/9/2017'),
    Duration: 1,
    Priority: 'Normal',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
    parentID: 10,
  },
  {
    TaskID: 15,
    TaskName: 'Child Task 5',
    StartDate: new Date('03/9/2017'),
    Duration: 14,
    Priority: 'Critical',
    EndDate: new Date('03/13/2017'),
    Progress: '40',
    parentID: 10,
  },
];

export let lineData: Object[] = [
  [0, 6, 4, 1, 3, 2, 5],
  [5, 4, 6, 3, 1, 2, 0],
  [6, 4, 0, 3, 2, 5, 1],
  [4, 6, 3, 0, 1, 2, 5],
  [3, 5, 6, 4, 0, 1, 2],
  [1, 3, 4, 2, 5, 0, 6],
  [2, 4, 0, 3, 5, 6, 1],
  [5, 4, 6, 3, 1, 2, 0],
  [0, 6, 4, 1, 3, 2, 5],
  [6, 4, 0, 3, 2, 5, 1],
  [4, 6, 3, 0, 1, 2, 5],
  [3, 5, 6, 4, 0, 1, 2],
  [1, 3, 4, 2, 5, 0, 6],
  [2, 4, 0, 3, 5, 6, 1],
  [5, 4, 6, 3, 1, 2, 0],
  [0, 6, 4, 1, 3, 2, 5],
  [6, 4, 0, 3, 2, 5, 1],
  [4, 6, 3, 0, 1, 2, 5],
  [2, 4, 0, 3, 5, 6, 1],
  [3, 5, 6, 4, 0, 1, 2],
  [1, 3, 4, 2, 5, 0, 6],
];
export let columnData: Object[] = [
  [0, 6, -4, 1, -3, 2, 5],
  [5, -4, 6, 3, -1, 2, 0],
  [6, 4, 0, 3, -2, 5, 1],
  [4, -6, 3, 0, 1, -2, 5],
  [3, 5, -6, -4, 0, 1, 2],
  [1, -3, 4, -2, 5, 0, 6],
  [2, 4, 0, -3, 5, -6, 1],
  [5, 4, -6, 3, 1, -2, 0],
  [0, -6, 4, 1, -3, 2, 5],
  [6, 4, 0, -3, 2, -5, 1],
  [4, 6, -3, 0, 1, 2, 5],
  [3, -5, -6, 4, 0, 1, 2],
  [1, 3, -4, -2, 5, 0, 6],
  [2, -4, 0, -3, 5, 6, 1],
  [5, 4, -6, 3, 1, -2, 0],
  [0, 6, 4, -1, -3, 2, 5],
  [6, -4, 0, -3, 2, 5, 1],
  [4, 6, -3, 0, -1, 2, 5],
  [6, 4, 0, -3, 2, -5, 1],
  [3, 5, 6, -4, 0, 1, 2],
  [1, 3, -4, 2, -5, 0, 6],
];
export let getSparkData: Function = (type: string, count: number) => {
  if (type === 'line') {
    return lineData[count];
  } else {
    return columnData[count];
  }
};
export let complexData: Object[] = [
  {
    taskID: 1,
    taskName: 'Planning',
    startDate: new Date('02/03/2017'),
    endDate: new Date('02/07/2017'),
    progress: 100,
    duration: 5,
    assignee: { firstName: 'Nancy', lastName: 'Davolio' },
    priority: 'Normal',
    approved: false,
    subtasks: [
      {
        taskID: 2,
        taskName: 'Plan timeline',
        startDate: new Date('02/03/2017'),
        assignee: { firstName: 'Andrew', lastName: 'Fuller' },
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 3,
        taskName: 'Plan budget',
        startDate: new Date('02/03/2017'),
        assignee: { firstName: 'Janet', lastName: 'Leverling' },
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 4,
        taskName: 'Allocate resources',
        startDate: new Date('02/03/2017'),
        assignee: { firstName: 'Margaret', lastName: 'Peacock' },
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 5,
        taskName: 'Planning complete',
        startDate: new Date('02/07/2017'),
        assignee: { firstName: 'Steven', lastName: 'Buchanan' },
        endDate: new Date('02/07/2017'),
        duration: 0,
        progress: 0,
        priority: 'Low',
        approved: true,
      },
    ],
  },
  {
    taskID: 6,
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    duration: 3,
    progress: 86,
    assignee: { firstName: 'Michael', lastName: 'Suyama' },
    priority: 'High',
    approved: false,
    subtasks: [
      {
        taskID: 7,
        taskName: 'Software Specification',
        startDate: new Date('02/10/2017'),
        assignee: { firstName: 'Robert', lastName: 'King' },
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 60,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 8,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        assignee: { firstName: 'Laura', lastName: 'Challahan' },
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 9,
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        assignee: { firstName: 'Anne', lastName: 'Dodsworth' },
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 10,
        taskName: 'Design Documentation',
        startDate: new Date('02/13/2017'),
        assignee: { firstName: 'Tamer', lastName: 'Nancy' },
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'High',
        approved: true,
      },
      {
        taskID: 11,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        assignee: { firstName: 'Laura', lastName: 'Martin' },
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: 0,
        priority: 'Normal',
        approved: true,
      },
    ],
  },
];

export let stringData: Object[] = [
  {
    taskID: 1,
    taskName: 'Planning',
    startDate: new Date('02/03/2017'),
    endDate: new Date('02/07/2017'),
    progress: 100,
    duration: 5,
    name: [{ firstName: 'Nancy' }, { lastName: 'Davolio' }],
    priority: 'Normal',
    approved: false,
    subtasks: [
      {
        taskID: 2,
        taskName: 'Plan timeline',
        startDate: new Date('02/03/2017'),
        name: [{ firstName: 'Andrew' }, { lastName: 'Fuller' }],
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 3,
        taskName: 'Plan budget',
        startDate: new Date('02/03/2017'),
        name: [{ firstName: 'Janet' }, { lastName: 'Leverling' }],
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 4,
        taskName: 'Allocate resources',
        startDate: new Date('02/03/2017'),
        name: [{ firstName: 'Margaret' }, { lastName: 'Peacock' }],
        endDate: new Date('02/07/2017'),
        duration: 5,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 5,
        taskName: 'Planning complete',
        startDate: new Date('02/07/2017'),
        name: [{ firstName: 'Steven' }, { lastName: 'Buchanan' }],
        endDate: new Date('02/07/2017'),
        duration: 0,
        progress: 0,
        priority: 'Low',
        approved: true,
      },
    ],
  },
  {
    taskID: 6,
    taskName: 'Design',
    startDate: new Date('02/10/2017'),
    endDate: new Date('02/14/2017'),
    duration: 3,
    progress: 86,
    name: [{ firstName: 'Michael' }, { lastName: 'Suyama' }],
    priority: 'High',
    approved: false,
    subtasks: [
      {
        taskID: 7,
        taskName: 'Software Specification',
        startDate: new Date('02/10/2017'),
        name: [{ firstName: 'Robert' }, { lastName: 'King' }],
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 60,
        priority: 'Normal',
        approved: false,
      },
      {
        taskID: 8,
        taskName: 'Develop prototype',
        startDate: new Date('02/10/2017'),
        name: [{ firstName: 'Laura' }, { lastName: 'Challahan' }],
        endDate: new Date('02/12/2017'),
        duration: 3,
        progress: 100,
        priority: 'Critical',
        approved: false,
      },
      {
        taskID: 9,
        taskName: 'Get approval from customer',
        startDate: new Date('02/13/2017'),
        name: [{ firstName: 'Anne' }, { lastName: 'Dodsworth' }],
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'Low',
        approved: true,
      },
      {
        taskID: 10,
        taskName: 'Design Documentation',
        startDate: new Date('02/13/2017'),
        name: [{ firstName: 'Tamer' }, { lastName: 'Nancy' }],
        endDate: new Date('02/14/2017'),
        duration: 2,
        progress: 100,
        priority: 'High',
        approved: true,
      },
      {
        taskID: 11,
        taskName: 'Design complete',
        startDate: new Date('02/14/2017'),
        name: [{ firstName: 'Laura' }, { lastName: 'Martin' }],
        endDate: new Date('02/14/2017'),
        duration: 0,
        progress: 0,
        priority: 'Normal',
        approved: true,
      },
    ],
  },
];

export let diacritics: Object[] = [
  {
    Name: 'Aeróbics',
    Designation: 'Chief Executive Officer',
    EmployeeID: '1',
    EmpID: 'EMP001',
    Address: '507 - 20th Ave. E.Apt. 2A, Seattle',
    Contact: '(206) 555-9857',
    Country: 'USA',
    DOB: new Date('2/15/1963'),

    Children: [
      {
        Name: 'Aerógrafía en Agua',
        Designation: 'Vice President',
        EmployeeID: '2',
        EmpID: 'EMP004',
        Address: '722 Moss Bay Blvd., Kirkland',
        Country: 'USA',
        Contact: '(206) 555-3412',
        DOB: new Date('5/20/1971'),

        Children: [
          {
            Name: 'AerografÃ­a',
            Designation: 'Marketing Executive',
            EmployeeID: '3',
            EmpID: 'EMP035',
            Address: '4110 Old Redmond Rd., Redmond',
            Country: 'USA',
            Contact: '(206) 555-8122',
            DOB: new Date('3/19/1966'),
            Children: [
              {
                Name: 'Aeromodelaje',
                Designation: 'Sales Representative',
                EmployeeID: '4',
                EmpID: 'EMP045',
                Address: '14 Garrett Hill, London',
                Country: 'UK',
                Contact: '(71) 555-4848',
                DOB: new Date('9/20/1980'),
              },
              {
                Name: 'Águilas',
                Designation: 'Sales Representative',
                EmployeeID: '5',
                EmpID: 'EMP091',
                Address: '4726 - 11th Ave. N.E., Seattle',
                Country: 'USA',
                Contact: '(206) 555-1189',
                DOB: new Date('10/19/1989'),
              },
              {
                Name: 'Álbumes de Delta',
                Designation: 'Sales Representative',
                EmployeeID: '6',
                EmpID: 'EMP110',
                Address: 'Coventry House Miner Rd., London',
                Country: 'UK',
                Contact: '(71) 555-3636',
                DOB: new Date('11/02/1987'),
              },
              {
                Name: 'Ãlbumes de Música',
                Designation: 'Sales Coordinator',
                EmployeeID: '7',
                EmpID: 'EMP131',
                Address: 'Edgeham Hollow Winchester Way, London',
                Country: 'UK',
                Contact: '(71) 555-3636',
                DOB: new Date('11/06/1990'),
              },
            ],
          },
          {
            Name: 'Alusivos',
            Designation: 'Sales Executive',
            EmployeeID: '8',
            EmpID: 'EMP039',
            Address: '7 Houndstooth Rd., London',
            Country: 'UK',
            Contact: '(71) 555-3690',
            DOB: new Date('02/02/1980'),
            Children: [
              {
                Name: 'Ãerografía',
                Designation: 'Sales Representative',
                EmployeeID: '9',
                EmpID: 'EMP213',
                Address: '4726 - 11th Ave. N.E., California',
                Country: 'USA',
                Contact: '(206) 555-1989',
                DOB: new Date('01/21/1986'),
              },
              {
                Name: 'Análisis de Escritura a Mano',
                Designation: 'Sales Coordinator',
                EmployeeID: '10',
                EmpID: 'EMP201',
                Address: 'Coventry House Miner Rd., London',
                Country: 'UK',
                Contact: '(71) 555-2222',
                DOB: new Date('12/01/1990'),
              },
              {
                Name: 'Aeromodelaje',
                Designation: 'Sales Representative',
                EmployeeID: '11',
                EmpID: 'EMP197',
                Address: '200 Lincoln Ave, Salinas, CA 93901',
                Country: 'USA',
                Contact: '(831) 758-7408',
                DOB: new Date('03/23/1987'),
              },
              {
                Name: 'Álbumes de Delta',
                Designation: 'Sales Representative',
                EmployeeID: '12',
                EmpID: 'EMP167',
                Address: '200 Lincoln Ave, Salinas, CA 93901',
                Country: 'USA',
                Contact: '(831) 758-7368 ',
                DOB: new Date('08/09/1989'),
              },
            ],
          },
        ],
      },
    ],
  },
];
export let hmData: Object[] = [
  {
    TaskID: 1,
    Crew: [
      {
        TaskID: 2,
        FIELD1: 'TOMSP',
        FIELD2: 1968,
        FIELD3: 176,
        FIELD4: 98,
        FIELD5: 909,
        FIELD6: 328,
        FIELD7: 76,
        FIELD8: 8,
        FIELD9: 9,
        FIELD10: 14,
        FIELD11: 25,
        FIELD12: 320,
        FIELD13: 5,
        FIELD14: 1,
        FIELD15: 812,
        FIELD16: 185,
        FIELD17: 274,
        FIELD18: 343,
        FIELD19: 436,
        FIELD20: 664,
        FIELD21: 627,
        FIELD22: 990,
        FIELD23: 235,
        FIELD24: 102,
        FIELD25: 645,
        FIELD26: 80,
        FIELD27: 180,
        FIELD28: 564,
        FIELD29: 292,
        FIELD30: 200,
      },
      {
        TaskID: 3,
        FIELD1: 'BOLID',
        FIELD2: 1969,
        FIELD3: 162,
        FIELD4: 78,
        FIELD5: 486,
        FIELD6: 320,
        FIELD7: 49,
        FIELD8: 1,
        FIELD9: 4,
        FIELD10: 55,
        FIELD11: 3,
        FIELD12: 843,
        FIELD13: 9,
        FIELD14: 4,
        FIELD15: 246,
        FIELD16: 80,
        FIELD17: 243,
        FIELD18: 353,
        FIELD19: 449,
        FIELD20: 565,
        FIELD21: 353,
        FIELD22: 23,
        FIELD23: 1776,
        FIELD24: 65,
        FIELD25: 156,
        FIELD26: 7,
        FIELD27: 346,
        FIELD28: 109,
        FIELD29: 195,
        FIELD30: 10,
      },
      {
        TaskID: 4,
        FIELD1: 'RICAR',
        FIELD2: 1970,
        FIELD3: 63,
        FIELD4: 13,
        FIELD5: 865,
        FIELD6: 23,
        FIELD7: 65,
        FIELD8: 1,
        FIELD9: 2,
        FIELD10: 96,
        FIELD11: 47,
        FIELD12: 441,
        FIELD13: 5,
        FIELD14: 5,
        FIELD15: 767,
        FIELD16: 73,
        FIELD17: 244,
        FIELD18: 207,
        FIELD19: 432,
        FIELD20: 104,
        FIELD21: 506,
        FIELD22: 886,
        FIELD23: 1424,
        FIELD24: 57,
        FIELD25: 267,
        FIELD26: 23,
        FIELD27: 128,
        FIELD28: 259,
        FIELD29: 326,
        FIELD30: 45,
      },
      {
        TaskID: 5,
        FIELD1: 'RATTC',
        FIELD2: 1971,
        FIELD3: 175,
        FIELD4: 70,
        FIELD5: 697,
        FIELD6: 451,
        FIELD7: 47,
        FIELD8: 2,
        FIELD9: 2,
        FIELD10: 10,
        FIELD11: 20,
        FIELD12: 675,
        FIELD13: 8,
        FIELD14: 1,
        FIELD15: 538,
        FIELD16: 88,
        FIELD17: 6,
        FIELD18: 288,
        FIELD19: 294,
        FIELD20: 297,
        FIELD21: 81,
        FIELD22: 801,
        FIELD23: 1070,
        FIELD24: 124,
        FIELD25: 671,
        FIELD26: 25,
        FIELD27: 203,
        FIELD28: 319,
        FIELD29: 170,
        FIELD30: 251,
      },
    ],
    FIELD1: 'LEHMS',
    FIELD2: 1967,
    FIELD3: 155,
    FIELD4: 61,
    FIELD5: 1074,
    FIELD6: 981,
    FIELD7: 20,
    FIELD8: 3,
    FIELD9: 9,
    FIELD10: 6,
    FIELD11: 54,
    FIELD12: 2,
    FIELD13: 2,
    FIELD14: 4,
    FIELD15: 201,
    FIELD16: 7,
    FIELD17: 248,
    FIELD18: 63,
    FIELD19: 486,
    FIELD20: 330,
    FIELD21: 175,
    FIELD22: 685,
    FIELD23: 842,
    FIELD24: 61,
    FIELD25: 542,
    FIELD26: 56,
    FIELD27: 124,
    FIELD28: 8,
    FIELD29: 465,
    FIELD30: 231,
  },
  {
    TaskID: 6,
    Crew: [
      {
        TaskID: 7,
        FIELD1: 'THEBI',
        FIELD2: 1973,
        FIELD3: 59,
        FIELD4: 3,
        FIELD5: 1386,
        FIELD6: 732,
        FIELD7: 85,
        FIELD8: 8,
        FIELD9: 6,
        FIELD10: 17,
        FIELD11: 71,
        FIELD12: 967,
        FIELD13: 8,
        FIELD14: 6,
        FIELD15: 858,
        FIELD16: 80,
        FIELD17: 62,
        FIELD18: 249,
        FIELD19: 451,
        FIELD20: 567,
        FIELD21: 90,
        FIELD22: 886,
        FIELD23: 1205,
        FIELD24: 117,
        FIELD25: 683,
        FIELD26: 32,
        FIELD27: 277,
        FIELD28: 251,
        FIELD29: 242,
        FIELD30: 281,
      },
      {
        TaskID: 8,
        FIELD1: 'ERNSH',
        FIELD2: 1974,
        FIELD3: 58,
        FIELD4: 3,
        FIELD5: 159,
        FIELD6: 267,
        FIELD7: 26,
        FIELD8: 8,
        FIELD9: 0,
        FIELD10: 66,
        FIELD11: 42,
        FIELD12: 364,
        FIELD13: 2,
        FIELD14: 7,
        FIELD15: 162,
        FIELD16: 98,
        FIELD17: 152,
        FIELD18: 73,
        FIELD19: 5,
        FIELD20: 314,
        FIELD21: 573,
        FIELD22: 523,
        FIELD23: 1470,
        FIELD24: 144,
        FIELD25: 891,
        FIELD26: 41,
        FIELD27: 242,
        FIELD28: 528,
        FIELD29: 160,
        FIELD30: 32,
      },
      {
        TaskID: 9,
        FIELD1: 'LEHMS',
        FIELD2: 1975,
        FIELD3: 12,
        FIELD4: 5,
        FIELD5: 1899,
        FIELD6: 854,
        FIELD7: 35,
        FIELD8: 8,
        FIELD9: 6,
        FIELD10: 91,
        FIELD11: 88,
        FIELD12: 706,
        FIELD13: 5,
        FIELD14: 4,
        FIELD15: 888,
        FIELD16: 108,
        FIELD17: 37,
        FIELD18: 24,
        FIELD19: 132,
        FIELD20: 21,
        FIELD21: 189,
        FIELD22: 335,
        FIELD23: 338,
        FIELD24: 129,
        FIELD25: 713,
        FIELD26: 12,
        FIELD27: 18,
        FIELD28: 361,
        FIELD29: 416,
        FIELD30: 289,
      },
      {
        TaskID: 10,
        FIELD1: 'SPLIR',
        FIELD2: 1976,
        FIELD3: 199,
        FIELD4: 70,
        FIELD5: 1775,
        FIELD6: 289,
        FIELD7: 61,
        FIELD8: 0,
        FIELD9: 0,
        FIELD10: 47,
        FIELD11: 83,
        FIELD12: 262,
        FIELD13: 2,
        FIELD14: 9,
        FIELD15: 235,
        FIELD16: 178,
        FIELD17: 271,
        FIELD18: 97,
        FIELD19: 73,
        FIELD20: 10,
        FIELD21: 256,
        FIELD22: 505,
        FIELD23: 1439,
        FIELD24: 48,
        FIELD25: 671,
        FIELD26: 81,
        FIELD27: 309,
        FIELD28: 119,
        FIELD29: 431,
        FIELD30: 230,
      },
    ],
    FIELD1: 'QUICK',
    FIELD2: 1972,
    FIELD3: 17,
    FIELD4: 93,
    FIELD5: 1092,
    FIELD6: 417,
    FIELD7: 65,
    FIELD8: 7,
    FIELD9: 0,
    FIELD10: 2,
    FIELD11: 15,
    FIELD12: 930,
    FIELD13: 0,
    FIELD14: 4,
    FIELD15: 22,
    FIELD16: 128,
    FIELD17: 298,
    FIELD18: 17,
    FIELD19: 322,
    FIELD20: 3,
    FIELD21: 607,
    FIELD22: 524,
    FIELD23: 628,
    FIELD24: 81,
    FIELD25: 362,
    FIELD26: 31,
    FIELD27: 80,
    FIELD28: 596,
    FIELD29: 429,
    FIELD30: 37,
  },
  {
    TaskID: 11,
    Crew: [
      {
        TaskID: 12,
        FIELD1: 'BERGS',
        FIELD2: 1968,
        FIELD3: 35,
        FIELD4: 99,
        FIELD5: 344,
        FIELD6: 357,
        FIELD7: 0,
        FIELD8: 2,
        FIELD9: 4,
        FIELD10: 58,
        FIELD11: 49,
        FIELD12: 134,
        FIELD13: 8,
        FIELD14: 2,
        FIELD15: 919,
        FIELD16: 49,
        FIELD17: 289,
        FIELD18: 223,
        FIELD19: 279,
        FIELD20: 45,
        FIELD21: 493,
        FIELD22: 109,
        FIELD23: 15,
        FIELD24: 37,
        FIELD25: 900,
        FIELD26: 40,
        FIELD27: 209,
        FIELD28: 45,
        FIELD29: 370,
        FIELD30: 286,
      },
      {
        TaskID: 13,
        FIELD1: 'VINET',
        FIELD2: 1969,
        FIELD3: 155,
        FIELD4: 83,
        FIELD5: 1528,
        FIELD6: 943,
        FIELD7: 65,
        FIELD8: 3,
        FIELD9: 8,
        FIELD10: 78,
        FIELD11: 17,
        FIELD12: 622,
        FIELD13: 7,
        FIELD14: 8,
        FIELD15: 200,
        FIELD16: 81,
        FIELD17: 171,
        FIELD18: 108,
        FIELD19: 239,
        FIELD20: 195,
        FIELD21: 57,
        FIELD22: 830,
        FIELD23: 1874,
        FIELD24: 116,
        FIELD25: 804,
        FIELD26: 23,
        FIELD27: 37,
        FIELD28: 416,
        FIELD29: 323,
        FIELD30: 77,
      },
      {
        TaskID: 14,
        FIELD1: 'RATTC',
        FIELD2: 1970,
        FIELD3: 50,
        FIELD4: 80,
        FIELD5: 385,
        FIELD6: 628,
        FIELD7: 16,
        FIELD8: 0,
        FIELD9: 2,
        FIELD10: 72,
        FIELD11: 25,
        FIELD12: 510,
        FIELD13: 9,
        FIELD14: 1,
        FIELD15: 219,
        FIELD16: 126,
        FIELD17: 207,
        FIELD18: 204,
        FIELD19: 489,
        FIELD20: 676,
        FIELD21: 232,
        FIELD22: 227,
        FIELD23: 781,
        FIELD24: 71,
        FIELD25: 167,
        FIELD26: 51,
        FIELD27: 97,
        FIELD28: 187,
        FIELD29: 436,
        FIELD30: 285,
      },
      {
        TaskID: 15,
        FIELD1: 'BLONP',
        FIELD2: 1971,
        FIELD3: 122,
        FIELD4: 97,
        FIELD5: 434,
        FIELD6: 449,
        FIELD7: 94,
        FIELD8: 3,
        FIELD9: 6,
        FIELD10: 63,
        FIELD11: 27,
        FIELD12: 146,
        FIELD13: 9,
        FIELD14: 8,
        FIELD15: 911,
        FIELD16: 78,
        FIELD17: 255,
        FIELD18: 142,
        FIELD19: 392,
        FIELD20: 372,
        FIELD21: 223,
        FIELD22: 515,
        FIELD23: 471,
        FIELD24: 13,
        FIELD25: 788,
        FIELD26: 73,
        FIELD27: 128,
        FIELD28: 475,
        FIELD29: 23,
        FIELD30: 21,
      },
    ],
    FIELD1: 'HUNGO',
    FIELD2: 1967,
    FIELD3: 172,
    FIELD4: 76,
    FIELD5: 205,
    FIELD6: 853,
    FIELD7: 76,
    FIELD8: 4,
    FIELD9: 4,
    FIELD10: 94,
    FIELD11: 78,
    FIELD12: 899,
    FIELD13: 1,
    FIELD14: 6,
    FIELD15: 58,
    FIELD16: 51,
    FIELD17: 133,
    FIELD18: 0,
    FIELD19: 374,
    FIELD20: 654,
    FIELD21: 685,
    FIELD22: 934,
    FIELD23: 193,
    FIELD24: 70,
    FIELD25: 322,
    FIELD26: 83,
    FIELD27: 211,
    FIELD28: 100,
    FIELD29: 483,
    FIELD30: 113,
  },
  {
    TaskID: 16,
    Crew: [
      {
        TaskID: 17,
        FIELD1: 'HUNGO',
        FIELD2: 1973,
        FIELD3: 93,
        FIELD4: 72,
        FIELD5: 1664,
        FIELD6: 377,
        FIELD7: 51,
        FIELD8: 0,
        FIELD9: 6,
        FIELD10: 28,
        FIELD11: 61,
        FIELD12: 596,
        FIELD13: 9,
        FIELD14: 3,
        FIELD15: 601,
        FIELD16: 152,
        FIELD17: 35,
        FIELD18: 219,
        FIELD19: 142,
        FIELD20: 296,
        FIELD21: 369,
        FIELD22: 713,
        FIELD23: 119,
        FIELD24: 35,
        FIELD25: 923,
        FIELD26: 35,
        FIELD27: 20,
        FIELD28: 226,
        FIELD29: 492,
        FIELD30: 72,
      },
      {
        TaskID: 18,
        FIELD1: 'RATTC',
        FIELD2: 1974,
        FIELD3: 36,
        FIELD4: 60,
        FIELD5: 651,
        FIELD6: 713,
        FIELD7: 12,
        FIELD8: 5,
        FIELD9: 5,
        FIELD10: 86,
        FIELD11: 71,
        FIELD12: 178,
        FIELD13: 4,
        FIELD14: 7,
        FIELD15: 676,
        FIELD16: 97,
        FIELD17: 168,
        FIELD18: 324,
        FIELD19: 136,
        FIELD20: 151,
        FIELD21: 787,
        FIELD22: 526,
        FIELD23: 1505,
        FIELD24: 28,
        FIELD25: 295,
        FIELD26: 35,
        FIELD27: 331,
        FIELD28: 518,
        FIELD29: 428,
        FIELD30: 106,
      },
      {
        TaskID: 19,
        FIELD1: 'GODOS',
        FIELD2: 1975,
        FIELD3: 158,
        FIELD4: 88,
        FIELD5: 1506,
        FIELD6: 244,
        FIELD7: 95,
        FIELD8: 8,
        FIELD9: 7,
        FIELD10: 22,
        FIELD11: 3,
        FIELD12: 120,
        FIELD13: 3,
        FIELD14: 8,
        FIELD15: 278,
        FIELD16: 67,
        FIELD17: 131,
        FIELD18: 252,
        FIELD19: 148,
        FIELD20: 560,
        FIELD21: 396,
        FIELD22: 131,
        FIELD23: 852,
        FIELD24: 101,
        FIELD25: 982,
        FIELD26: 6,
        FIELD27: 380,
        FIELD28: 426,
        FIELD29: 382,
        FIELD30: 38,
      },
      {
        TaskID: 20,
        FIELD1: 'RATTC',
        FIELD2: 1976,
        FIELD3: 3,
        FIELD4: 76,
        FIELD5: 575,
        FIELD6: 382,
        FIELD7: 57,
        FIELD8: 1,
        FIELD9: 7,
        FIELD10: 21,
        FIELD11: 42,
        FIELD12: 544,
        FIELD13: 6,
        FIELD14: 7,
        FIELD15: 938,
        FIELD16: 189,
        FIELD17: 2,
        FIELD18: 290,
        FIELD19: 310,
        FIELD20: 489,
        FIELD21: 725,
        FIELD22: 74,
        FIELD23: 728,
        FIELD24: 146,
        FIELD25: 367,
        FIELD26: 66,
        FIELD27: 111,
        FIELD28: 318,
        FIELD29: 492,
        FIELD30: 222,
      },
    ],
    FIELD1: 'RATTC',
    FIELD2: 1972,
    FIELD3: 183,
    FIELD4: 45,
    FIELD5: 1663,
    FIELD6: 376,
    FIELD7: 63,
    FIELD8: 2,
    FIELD9: 2,
    FIELD10: 72,
    FIELD11: 22,
    FIELD12: 769,
    FIELD13: 1,
    FIELD14: 2,
    FIELD15: 678,
    FIELD16: 98,
    FIELD17: 151,
    FIELD18: 367,
    FIELD19: 349,
    FIELD20: 393,
    FIELD21: 408,
    FIELD22: 169,
    FIELD23: 1982,
    FIELD24: 104,
    FIELD25: 97,
    FIELD26: 84,
    FIELD27: 202,
    FIELD28: 141,
    FIELD29: 416,
    FIELD30: 137,
  },
];
